from app.models import db, Stock  

def seed_stocks():
    list_stocks = [ Stock(ticker="TSLA", name="Tesla"),
    Stock(ticker="AAPL", name="Apple"),
    Stock(ticker="MSFT", name="Microsoft"),
    Stock(ticker="AMZN", name="Amazon"),
    Stock(ticker="ZM", name="Zoom"),
    Stock(ticker="HOOD", name="Robinhood Markets"),
    Stock(ticker="GOOGL", name="Alphabet Class A"),
    Stock(ticker="GOOG", name="Alphabet Class C"),
    Stock(ticker="FB", name="Facebook"),
    Stock(ticker="TSM", name="Taiwan Semiconductor Manufacturing"),
    Stock(ticker="BABA", name="Alibaba"),
    Stock(ticker="GM", name="General Motors"),
    Stock(ticker="GME", name="GameStop"),
    Stock(ticker="AMC", name="AMC Entertainment"),
    Stock(ticker="ZTS", name="Zoetis"),
    Stock(ticker="ABNB", name="Airbnb"),
    Stock(ticker="TWTR", name="Twitter"),
    Stock(ticker="HMC", name="Honda"),
    Stock(ticker="SPOT", name="Spotify"),
    Stock(ticker="FDX", name="FedEx"),
    Stock(ticker="ROST", name="Ross"),
    Stock(ticker="JPM", name="JPMorgan Chase"),
    Stock(ticker="DOW", name="Dow"),
    Stock(ticker="V", name="Visa"),
    Stock(ticker="DASH", name="DoorDash"),
    Stock(ticker="NOK", name="Nokia"),
    Stock(ticker="RBLX", name="Roblox"),
    Stock(ticker="KHC", name="Kraft Foods"),
    Stock(ticker="BMWYY", name="BMW"),
    Stock(ticker="BLNK", name="Blink Charging"),
    Stock(ticker="FSR", name="Fisker"),
    Stock(ticker="FLDM", name="Fluidigm"),
    Stock(ticker="TNXP", name="Tonix Pharmaceuticals"),
    Stock(ticker="ASXC", name="Asensus Surgical"),
    Stock(ticker="BYDDY", name="BYD Company"),
    Stock(ticker="IBIO", name="iBio"),
    Stock(ticker="SLV", name="iShares Silver trust"),
    Stock(ticker="EHTH", name="eHealth"),
    Stock(ticker="SVM", name="Silvercorp Metals"),
    Stock(ticker="EXPR", name="Express"),
    Stock(ticker="CYRX", name="CryoPort"),
    Stock(ticker="PLAY", name="Dave & Buster's"),
    Stock(ticker="GNUS", name="Genius Brands"),
    Stock(ticker="TLRY", name="Tilray"),
    Stock(ticker="BMRN", name="BioMarin"),
    Stock(ticker="NKLA", name="Nikola"),
    Stock(ticker="BBBY", name="Bed Bath & Beyond"),
    Stock(ticker="M", name="Macy's"),
    Stock(ticker="UA", name="Under Armour"),
    Stock(ticker="SNDL", name="Sundial Growers"),
    Stock(ticker="ACB", name="Aurora Cannabis"),
    Stock(ticker="ZOM", name="Zomedica"),
    Stock(ticker="GPRO", name="GoPro"),
    Stock(ticker="OGI", name="OrganiGram"),
    Stock(ticker="NAKD", name="Naked Brand"),
    Stock(ticker="BAC", name="Bank of America"),
    Stock(ticker="CGC", name="Canopy Growth"),
    Stock(ticker="FCEL", name="FuelCell Energy"),
    Stock(ticker="SPCE", name="Virgin Galactic Holdings"),
    Stock(ticker="IDEX", name="Ideanomics"),
    Stock(ticker="NCLH", name="Norwegian Cruise Line"),
    Stock(ticker="VOO", name="Vanguard S&P 500 ETF"),
    Stock(ticker="SPY", name="SPDR S&P 500 ETF"),
    Stock(ticker="ZNGA", name="Zynga"),
    Stock(ticker="BB", name="Blackberry"),
    Stock(ticker="PSEC", name="Prospect Capital"),
    Stock(ticker="CRON", name="Cronos Group"),
    Stock(ticker="OCGN", name="Ocugen"),
    Stock(ticker="BNGO", name="Bionano Genomics"),
    Stock(ticker="ARKK", name="ARK Innovation ETF"),
    Stock(ticker="TXMD", name="TherapeuticsMD"),
    Stock(ticker="MRO", name="Marathon Oil"),
    Stock(ticker="RIOT", name="Riot Blockchain"),
    Stock(ticker="HEXO", name="HEXO"),
    Stock(ticker="JBLU", name="JetBlue Airways"),
    Stock(ticker="CPRX", name="Catalyst Pharmaceuticals"),
    Stock(ticker="RYCEY", name="Rolls-Royce"),
    Stock(ticker="NNDM", name="Nano Dimension"),
    Stock(ticker="ET", name="Energy Transfer"),
    Stock(ticker="VTI", name="Vanguard Total Stock Market ETF"),
    Stock(ticker="SOS", name="SOS Limited"),
    Stock(ticker="CHPT", name="ChargePoint"),
    Stock(ticker="MVIS", name="MicroVision"),
    Stock(ticker="IVR", name="Invesco Mortgage Capital"),
    Stock(ticker="NRZ", name="New Residential Invesment"),
    Stock(ticker="SAVE", name="Spirit Airlines"),
    Stock(ticker="SENS", name="Senseonics"),
    Stock(ticker="GSAT", name="Globalstar"),
    Stock(ticker="PENN", name="Penn National Gambling"),
    Stock(ticker="INO", name="Inovio"),
    Stock(ticker="GOOS", name="Canada Goose"),
    Stock(ticker="SPPI", name="Spectrum Pharmaceuticals"),
    Stock(ticker="EPIX", name="Essa Pharma"),
    Stock(ticker="GH", name="Guardant Health"),
    Stock(ticker="POSH", name="Poshmark"),
    Stock(ticker="WOOF", name="Petco Health and Wellness"),
    Stock(ticker="INPX", name="Inpixon"),
    Stock(ticker="LU", name="Lufax"),
    Stock(ticker="BLUE", name="Bluebird bio"),
    Stock(ticker="WISH", name="ContextLogic"),
    Stock(ticker="NOVA", name="Sunnova Energy"),
    Stock(ticker="PAAS", name="Pan American Silver"),
    Stock(ticker="OTLK", name="Outlook Therapeutics"),
    Stock(ticker="ARPO", name="Aerpio Pharmaceuticals"),
    Stock(ticker="LPCN", name="Lipocine"),
    Stock(ticker="CRBP", name="Corbus Pharmaceuticals"),
    Stock(ticker="OVID", name="Ovid Therapeutics"),
    Stock(ticker="ACST", name="Acasti Pharma"),
    Stock(ticker="TRCH", name="Torchlight Energy Resources"),
    Stock(ticker="BMBL", name="Bumble"),
    Stock(ticker="VXRT", name="Vaxart"),
    Stock(ticker="JNJ", name="Johnson & Johnson"),
    Stock(ticker="NVDA", name="NVIDIA"),
    Stock(ticker="WMT", name="Walmart"),
    Stock(ticker="KDP", name="Keurig Dr Pepper"),
    Stock(ticker="PINS", name="Pinterest"),
    Stock(ticker="SNAP", name="Snap"),
    Stock(ticker="WBA", name="Walgreens"),
    Stock(ticker="NDAQ", name="Nasdaq"),
    Stock(ticker="UNH", name="UnitedHealth"),
    Stock(ticker="TWLO", name="Twilio"),
    Stock(ticker="WORK", name="Slack"),
    Stock(ticker="F", name="Ford Motor"),
    Stock(ticker="MA", name="Mastercard"),
    Stock(ticker="HD", name="Home Depot"),
    Stock(ticker="PG", name="Procter & Gamble"),
    Stock(ticker="HSY", name="Hershey"),
    Stock(ticker="DFS", name="Discover"),
    Stock(ticker="DIS", name="Disney"),
    Stock(ticker="EA", name="Electronic Artis"),
    Stock(ticker="CMG", name="Chipotle"),
    Stock(ticker="SRE", name="Sempra Energy"),
    Stock(ticker="UBER", name="Uber"),
    Stock(ticker="MAR", name="Mariott"),
    Stock(ticker="LULU", name="Lululemon Athletica"),
    Stock(ticker="PYPL", name="PayPal"),
    Stock(ticker="ASML", name="ASML Holding"),
    Stock(ticker="ZIP", name="ZipRecruiter"),
    Stock(ticker="CMCSA", name="Comcast"),
    Stock(ticker="XOM", name="Exxon Mobil"),
    Stock(ticker="AZO", name="AutoZone"),
    Stock(ticker="ZG", name="Zillow Class A"),
    Stock(ticker="Z", name="Zillow Class C"),
    Stock(ticker="DKNG", name="DraftKings"),
    Stock(ticker="DAL", name="Delta Air Lines"),
    Stock(ticker="SONY", name="Sony"),
    Stock(ticker="GE", name="General Electric"),
    Stock(ticker="ROKU", name="Roku"),
    Stock(ticker="ADBE", name="Adobe"),
    Stock(ticker="KO", name="Coca-Cola"),
    Stock(ticker="VZ", name="Verizon"),
    Stock(ticker="ETSY", name="Etsy"),
    Stock(ticker="ATVI", name="Activision Blizzard"),
    Stock(ticker="TM", name="Toyota"),
    Stock(ticker="INTC", name="Intel"),
    Stock(ticker="ORCL", name="Oracle"),
    Stock(ticker="CVS", name="CVS Health"),
    Stock(ticker="ALL", name="Allstate"),
    Stock(ticker="CSCO", name="Cisco"),
    Stock(ticker="MNST", name="Monster"),
    Stock(ticker="DISCB", name="Discovery"),
    Stock(ticker="UAL", name="United Airlines"),
    Stock(ticker="NFLX", name="Netflix"),
    Stock(ticker="BBY", name="Best Buy"),
    Stock(ticker="CRM", name="Salesforce"),
    Stock(ticker="PFE", name="Pfizer"),
    Stock(ticker="CHWY", name="Chewy"),
    Stock(ticker="BCS", name="Barclays"),
    Stock(ticker="RACE", name="Ferrari"),
    Stock(ticker="NKE", name="Nike"),
    Stock(ticker="LYFT", name="Lyft"),
    Stock(ticker="SQ", name="Square"),
    Stock(ticker="T", name="AT&T"),
    Stock(ticker="ABT", name="Abbot Laboratories"),
    Stock(ticker="LUV", name="Southwest Airlines"),
    Stock(ticker="PEP", name="Pepsi"),
    Stock(ticker="CVX", name="Chevron"),
    Stock(ticker="COIN", name="Coinbase"),
    Stock(ticker="ABV", name="AbbVie"),
    Stock(ticker="NVS", name="Novartis AG"),
    Stock(ticker="EXPE", name="Expedia"),
    Stock(ticker="WFC", name="Wells Fargo"),
    Stock(ticker="AVGO", name="Broadcom"),
    Stock(ticker="DUOL", name="Duolingo"),
    Stock(ticker="CVNA", name="Carvano"),
    Stock(ticker="MRK", name="Merck"),
    Stock(ticker="OKTA", name="Okta"),
    Stock(ticker="LLY", name="Eli Lilly"),
    Stock(ticker="BHP", name="BHP Group"),
    Stock(ticker="UPS", name="United Parcel Service"),
    Stock(ticker="TMO", name="Thermo Fisher Scientific"),
    Stock(ticker="DHR", name="Danaher"),
    Stock(ticker="NVO", name="Novo Nordisk"),
    Stock(ticker="ACN", name="Accenture plc Class A"),
    Stock(ticker="TMUS", name="T-Mobile"),
    Stock(ticker="TXN", name="Texas Instruments"),
    Stock(ticker="MCD", name="McDonald's"),
    Stock(ticker="PLUG", name="Plug Power"),
    Stock(ticker="MDB", name="MongoDB"),
    Stock(ticker="MDT", name="Medtronic"),
    Stock(ticker="DLTR", name="Dollar Tree"),
    Stock(ticker="MS", name="Morgan Stanley"),
    Stock(ticker="K", name="Kellogg"),
    Stock(ticker="COST", name="Costco Wholesale"),
    Stock(ticker="SAP", name="SAP SE"),
    Stock(ticker="CLX", name="Clorox"),
    Stock(ticker="C", name="Citigroup"),
    Stock(ticker="HON", name="Honeywell"),
    Stock(ticker="UL", name="Unilever PLC"),
    Stock(ticker="LIN", name="Linde"),
    Stock(ticker="GIS", name="General Mills"),
    Stock(ticker="XEL", name="Xcel Energy"),
    Stock(ticker="LOGI", name="Logitech"),
    Stock(ticker="TGT", name="Target"),
    Stock(ticker="NET", name="Cloudflare"),
    Stock(ticker="IRBT", name="iRobot"),
    Stock(ticker="UPWK", name="Upwork"),
    Stock(ticker="RDFN", name="Redfin"),
    Stock(ticker="FVRR", name="Fiverr"),
    Stock(ticker="BYND", name="Beyond Meat"),
    Stock(ticker="ISRG", name="Intuitive Surgical"),
    Stock(ticker="BRK.A", name="Berkshire Hathaway"),
    Stock(ticker="BRK.B", name="Berkshire Hathaway"),
    Stock(ticker="DPZ", name="Domino's Pizza"),
    Stock(ticker="SNOW", name="Snowflake"),
    Stock(ticker="SHOP", name="Shopify"),
    Stock(ticker="BBL", name="BHP Group"),
    Stock(ticker="QCOM", name="QUALCOMM"),
    Stock(ticker="PM", name="Philip Morris"),
    Stock(ticker="BUD", name="Anheuser-Busch Inbev"),
    Stock(ticker="UNP", name="Union Pacific"),
    Stock(ticker="AZN", name="AstraZeneca"),
    Stock(ticker="MTCH", name="Match"),
    Stock(ticker="RY", name="Royal Bank of Canada"),
    Stock(ticker="DOCU", name="DocuSign"),
    Stock(ticker="BMY", name="Bristol-Myers Squibb"),
    Stock(ticker="BA", name="Boeing"),
    Stock(ticker="NEE", name="NextEra Energy"),
    Stock(ticker="CHTR", name="Charter Communications"),
    Stock(ticker="CCIV", name="Churchill Capital"),
    Stock(ticker="PLTR", name="Palantir Technologies"),
    Stock(ticker="LI", name="Li Auto"),
    Stock(ticker="XPEV", name="Xpeng"),
    Stock(ticker="ULTA", name="Ulta Beauty"),
    Stock(ticker="FUBO", name="Fubo"),
    Stock(ticker="WKHS", name="Workhorse"),
    Stock(ticker="LB", name="L Brands"),
    Stock(ticker="RIO", name="Rio Tinto"),
    Stock(ticker="HDB", name="HDFC Bank"),
    Stock(ticker="SCHW", name="Charles Schwab"),
    Stock(ticker="LOW", name="Lowe's"),
    Stock(ticker="AMGN", name="Amgen"),
    Stock(ticker="RTX", name="Raytheon Technologies"),
    Stock(ticker="SBUX", name="Starbucks"),
    Stock(ticker="SKM", name="SK Telecom"),
    Stock(ticker="BLK", name="BlackRock"),
    Stock(ticker="SNY", name="Sanofi"),
    Stock(ticker="SE", name="Sea Limited AMerican Depositary Shares"),
    Stock(ticker="HSBC", name="HSBC Holdings"),
    Stock(ticker="CAT", name="Caterpillar"),
    Stock(ticker="TD", name="Toronto Dominion Bank"),
    Stock(ticker="SIRI", name="Sirius XM"),
    Stock(ticker="AXP", name="American Express"),
    Stock(ticker="KMX", name="CarMax"),
    Stock(ticker="IBM", name="International Business Machines"),
    Stock(ticker="AMAT", name="Applied Materials"),
    Stock(ticker="GS", name="Goldman Sachs"),
    Stock(ticker="CSAN", name="Cosan"),
    Stock(ticker="TOT", name="Total"),
    Stock(ticker="INTU", name="Intuit"),
    Stock(ticker="AAL", name="American Airlines"),
    Stock(ticker="MMM", name="3M"),
    Stock(ticker="AMT", name="American Tower"),
    Stock(ticker="JD", name="JD.com"),
    Stock(ticker="KR", name="Kroger"),
    Stock(ticker="TTD", name="The Trade Desk"),
    Stock(ticker="DE", name="Deere & Company"),
    Stock(ticker="DEO", name="Diaegeo"),
    Stock(ticker="BURL", name="Burlington Stores"),
    Stock(ticker="EL", name="Estee Lauder"),
    Stock(ticker="DISH", name="DISH Network"),
    Stock(ticker="VALE", name="Vale"),
    Stock(ticker="Real", name="The RealReal"),
    Stock(ticker="LMT", name="Lockheed Martin"),
    Stock(ticker="AMCX", name="AMC Networks"),
    Stock(ticker="DIT", name="Amcon Distributing"),
    Stock(ticker="ZI", name="ZoomInfo"),
    Stock(ticker="GSK", name="GlaxoSmithKline"),
    Stock(ticker="ANTM", name="Anthem"),
    Stock(ticker="AMD", name="Advanced Micro Devices"),
    Stock(ticker="CZR", name="Caesars Entertainment"),
    Stock(ticker="FOXA", name="Fox Class A"),
    Stock(ticker="FOX", name="Fox Class B"),
    Stock(ticker="SNA", name="Snap-On"),
    Stock(ticker="NTAP", name="NetApp"),
    Stock(ticker="BKNG", name="Booking Holdings"),
    Stock(ticker="SYK", name="Stryker"),
    Stock(ticker="MGM", name="MGM Resorts"),
    Stock(ticker="MU", name="Micron"),
    Stock(ticker="NOW", name="ServiceNow"),
    Stock(ticker="LCRX", name="Lam Research"),
    Stock(ticker="FIS", name="Fidelity"),
    Stock(ticker="SPGI", name="S&P Global"),
    Stock(ticker="MO", name="Altria"),
    Stock(ticker="USB", name="US Bank"),
    Stock(ticker="MDLZ", name="Mondelez International"),
    Stock(ticker="BTI", name="British American Tobacco Industry"),
    Stock(ticker="BP", name="BP plc"),
    Stock(ticker="CI", name="Cigna"),
    Stock(ticker="PLD", name="Prologis"),
    Stock(ticker="ADP", name="Automatic Data Processing"),
    Stock(ticker="TFC", name="Truist Financial"),
    Stock(ticker="GILD", name="Gilead Sciences"),
    Stock(ticker="PNC", name="PNC Financial Services Group"),
    Stock(ticker="INFY", name="Infosys"),
    Stock(ticker="CCI", name="Crown Castle International"),
    Stock(ticker="BNS", name="Bank of Nova Scotia"),
    Stock(ticker="TJX", name="TJX Companies"),
    Stock(ticker="CNI", name="Canadian National Railway"),
    Stock(ticker="BAM", name="Brookfield Asset Management"),
    Stock(ticker="NTES", name="NetEase"),
    Stock(ticker="CME", name="CME Group"),
    Stock(ticker="CB", name="Chubb Limited"),
    Stock(ticker="FISV", name="Fiserv"),
    Stock(ticker="CSX", name="CSX Corporation"),
    Stock(ticker="PTR", name="PetroChina"),
    Stock(ticker="SHW", name="Sherwin-Williams"),
    Stock(ticker="DELL", name="Dell"),
    Stock(ticker="COP", name="ConocoPhillips"),
    Stock(ticker="WBK", name="Westpac Banking"),
    Stock(ticker="MUFG", name="Mitsubishi"),
    Stock(ticker="MRNA", name="Moderna"),
    Stock(ticker="ITW", name="Illinois Tools Works"),
    Stock(ticker="SAN", name="Banco Santander"),
    Stock(ticker="COF", name="Capital One Financial"),
    Stock(ticker="EQNR", name="Equinor"),
    Stock(ticker="HCA", name="HCA HealthCare"),
    Stock(ticker="CL", name="Colgate"),
    Stock(ticker="CPNG", name="Coupang"),
    Stock(ticker="MMC", name="Marsh & McLennan"),
    Stock(ticker="BDX", name="Becton, Dickinson & Company"),
    Stock(ticker="NSC", name="Norfolk Southern Corporation"),
    Stock(ticker="ABB", name="Abb Ltd"),
    Stock(ticker="BIDU", name="Baidu"),
    Stock(ticker="BMO", name="Bank of Montreal"),
    Stock(ticker="MELI", name="MercadoLibre"),
    Stock(ticker="SO", name="Southern Company"),
    Stock(ticker="PBR", name="Petroleo Brasileiro"),
    Stock(ticker="APD", name="Air Products and Chemicals"),
    Stock(ticker="VMW", name="Vmware"),
    Stock(ticker="EQIX", name="Equinix"),
    Stock(ticker="SNP", name="China Petroleum & Chemical Corporation"),
    Stock(ticker="BX", name="The Blackstone Group"),
    Stock(ticker="ICE", name="Intercontinental Exchange"),
    Stock(ticker="ADSK", name="Autodesk"),
    Stock(ticker="MCO", name="Moody's"),
    Stock(ticker="FCX", name="Freeport-McMoRan"),
    Stock(ticker="IBN", name="ICICI Bank"),
    Stock(ticker="BEKE", name="KE Holdings"),
    Stock(ticker="ECL", name="Ecolab"),
    Stock(ticker="D", name="Doiminion Energy"),
    Stock(ticker="STLA", name="Stellantis"),
    Stock(ticker="ADI", name="Analog Devices"),
    Stock(ticker="LFC", name="China Life Insurance"),
    Stock(ticker="BSX", name="Boston Scientific"),
    Stock(ticker="EW", name="Edwards Lifesciences"),
    Stock(ticker="WM", name="Waste Management"),
    Stock(ticker="ILMN", name="Illumina"),
    Stock(ticker="BSBR", name="Banco Santander Brasil"),
    Stock(ticker="NOC", name="Northrop Grumman"),
    Stock(ticker="TEAM", name="Atlassian"),
    Stock(ticker="NXPI", name="NXP Semiconductors"),
    Stock(ticker="PGR", name="Progressive"),
    Stock(ticker="ETN", name="Eaton"),
    Stock(ticker="UBS", name="UBS Group"),
    Stock(ticker="EMR", name="Emerson Electric"),
    Stock(ticker="MET", name="MetLife"),
    Stock(ticker="GPN", name="Globaal Payments"),
    Stock(ticker="AON", name="Aon"),
    Stock(ticker="HUM", name="Humana"),
    Stock(ticker="PUK", name="Prudential Public"),
    Stock(ticker="WDAY", name="Workday"),
    Stock(ticker="ITUB", name="Itau Unibanco"),
    Stock(ticker="ING", name="ING"),
    Stock(ticker="ABEV", name="Ambev"),
    Stock(ticker="CP", name="Canadian Pacific Railway"),
    Stock(ticker="VRTX", name="Vertex Pharmaceuticals"),
    Stock(ticker="SCCO", name="Southern Copper"),
    Stock(ticker="TAK", name="Takeda Pharmaceutical"),
    Stock(ticker="GD", name="General Dynamics"),
    Stock(ticker="REGN", name="Regeneron Pharmaceuticals"),
    Stock(ticker="CM", name="Canadian Imperial Bank of Commerce"),
    Stock(ticker="VOD", name="Vodafone"),
    Stock(ticker="EPD", name="Enterprise Products"),
    Stock(ticker="PHG", name="Royal Philips"),
    Stock(ticker="AMX", name="America Movil"),
    Stock(ticker="RELX", name="RELX"),
    Stock(ticker="AMOV", name="American Movil"),
    Stock(ticker="SMFG", name="Sumitomo Mitsui"),
    Stock(ticker="CRWD", name="CrowdStrike"),
    Stock(ticker="TRP", name="TC Energy"),
    Stock(ticker="LYG", name="Lloyds Banking"),
    Stock(ticker="PSA", name="Public Storage"),
    Stock(ticker="BBD", name="Banco Bradesco"),
    Stock(ticker="BNTX", name="BioNTech"),
    Stock(ticker="KLAC", name="KLA"),
    Stock(ticker="DG", name="Dollar General"),
    Stock(ticker="TRI", name="Thomson Reuters"),
    Stock(ticker="JCI", name="Johnson Controls International"),
    Stock(ticker="IDXX", name="IDEXX Laboratories"),
    Stock(ticker="NGG", name="National Grid Transco"),
    Stock(ticker="ROP", name="Roper"),
    Stock(ticker="EOG", name="EOG Resources"),
    Stock(ticker="ALGN", name="Align"),
    Stock(ticker="STZ", name="Constellation Brands"),
    Stock(ticker="IQV", name="IQVIA Holdings"),
    Stock(ticker="BK", name="The Bank of New York Mellon"),
    Stock(ticker="AIG", name="American International Group"),
    Stock(ticker="DD", name="DuPont de Nemours"),
    Stock(ticker="BCE", name="BCE"),
    Stock(ticker="TEL", name="TE Connectivity"),
    Stock(ticker="ERIC", name="Ericsson"),
    Stock(ticker="LHX", name="L3Harris"),
    Stock(ticker="INFO", name="IHS Markit"),
    Stock(ticker="VEEV", name="Veeva Systems"),
    Stock(ticker="LVS", name="Las Vegas Sands"),
    Stock(ticker="EXC", name="Exelon"),
    Stock(ticker="KMB", name="Kimberly-Clark"),
    Stock(ticker="E", name="Eni"),
    Stock(ticker="SLB", name="Schlumberger"),
    Stock(ticker="TROW", name="T.Rowe Price"),
    Stock(ticker="WIT", name="Wipro"),
    Stock(ticker="AEP", name="American Electric Power"),
    Stock(ticker="MCHP", name="Microchip Technology"),
    Stock(ticker="CNC", name="Centene"),
    Stock(ticker="GOLD", name="Barrick Gold"),
    Stock(ticker="DLR", name="Digital Realty Trust"),
    Stock(ticker="PPG", name="PPG"),
    Stock(ticker="BBDO", name="Banco Bradesco"),
    Stock(ticker="SPG", name="Simon Property Group"),
    Stock(ticker="PRU", name="Prudential Financial"),
    Stock(ticker="A", name="Agilent"),
    Stock(ticker="KMI", name="Kinder Morgan"),
    Stock(ticker="BBVA", name="Banco Bilbao"),
    Stock(ticker="PATH", name="UiPath"),
    Stock(ticker="SYY", name="Sysco"),
    Stock(ticker="BAX", name="Baxter"),
    Stock(ticker="CNQ", name="Canadian Natural Resources"),
    Stock(ticker="CRH", name="CRH"),
    Stock(ticker="APTV", name="Aptiv"),
    Stock(ticker="BILI", name="Bilibili"),
    Stock(ticker="MFC", name="Manulife"),
    Stock(ticker="MPC", name="Marathon Petroleum"),
    Stock(ticker="BIIB", name="Biogen"),
    Stock(ticker="APH", name="Amphenol"),
    Stock(ticker="TRV", name="Travelers"),
    Stock(ticker="CARR", name="Carrier Global"),
    Stock(ticker="PH", name="Parker-Hannifin"),
    Stock(ticker="MFG", name="Mizuho"),
    Stock(ticker="ALXN", name="Alexion"),
    Stock(ticker="SNPS", name="Synopsys"),
    Stock(ticker="MSCI", name="MSCI"),
    Stock(ticker="CTSH", name="Cognizant"),
    Stock(ticker="LYB", name="LyondelBassel"),
    Stock(ticker="CMI", name="Cummins"),
    Stock(ticker="ORLY", name="O'Reilly"),
    Stock(ticker="ADM", name="Archer-Daniels-Midland"),
    Stock(ticker="GLW", name="Corning"),
    Stock(ticker="CTAS", name="Cintas"),
    Stock(ticker="PXD", name="Pioneer"),
    Stock(ticker="PSX", name="Phillips 66"),
    Stock(ticker="PAYX", name="Paychex"),
    Stock(ticker="HPQ", name="HP"),
    Stock(ticker="YUM", name="Yum!"),
    Stock(ticker="DXCM", name="DexCom"),
    Stock(ticker="FTNT", name="Fortinet"),
    Stock(ticker="TDG", name="Transdigm"),
    Stock(ticker="NTR", name="Nutrien"),
    Stock(ticker="PANW", name="Palo Alto Networks"),
    Stock(ticker="CDNS", name="Cadence Design Systems"),
    Stock(ticker="IFF", name="International Flavors & Fragrances"),
    Stock(ticker="CCL", name="Carnival"),
    Stock(ticker="ZBH", name="Zimmer Biomet"),
    Stock(ticker="SWK", name="Stanley Black & Decker"),
    Stock(ticker="HLT", name="Hilton Worldwide Holdings"),
    Stock(ticker="MSI", name="Motorola Solutions"),
    Stock(ticker="RSG", name="Reupublic Services"),
    Stock(ticker="ALC", name="Alcon"),
    Stock(ticker="SU", name="Suncor Energy"),
    Stock(ticker="MT", name="Arcelor Mittal"),
    Stock(ticker="NWG", name="NatWest"),
    Stock(ticker="DHI", name="D.R. Horton"),
    Stock(ticker="ORAN", name="Orange"),
    Stock(ticker="FRC", name="FIRST REPUBLIC BANK"),
    Stock(ticker="CSGP", name="CoStar Group"),
    Stock(ticker="WLTW", name="Willis Towers Watson"),
    Stock(ticker="OTIS", name="Otis"),
    Stock(ticker="BASE", name="Couchbase"),
    Stock(ticker="ERAS", name="Erasca"),
    Stock(ticker="BLND", name="Blend Labs"),
    Stock(ticker="STM", name="STMicroelectronics"),
    Stock(ticker="CTVA", name="Corteva"),
    Stock(ticker="BGNE", name="BeiGene"),
    Stock(ticker="PTON", name="Peloton"),
    Stock(ticker="DNUT", name="Krispy Kreme"),
    Stock(ticker="VLO", name="Valero Energy"),
    Stock(ticker="WKME", name="WalkMe"),
    Stock(ticker="MRVL", name="Marvell Tecnhology"),
    Stock(ticker="SBAC", name="SBA Communications"),
    Stock(ticker="KKR", name="KKR"),
    Stock(ticker="WMB", name="Williams Companies"),
    Stock(ticker="W", name="Wayfair"),
    Stock(ticker="PCAR", name="PACCAR"),
    Stock(ticker="CHT", name="Chunghwa Telecom"),
    Stock(ticker="WCN", name="Waste Connections"),
    Stock(ticker="SIVB", name="SVB"),
    Stock(ticker="DB", name="Deutsche Bank"),
    Stock(ticker="SLF", name="Sun Life"),
    Stock(ticker="LBRDK", name="Liberty Broadband"),
    Stock(ticker="PEG", name="Public Service Enterprise"),
    Stock(ticker="VFC", name="V.F. Corporation"),
    Stock(ticker="XLNX", name="Xilinx"),
    Stock(ticker="WELL", name="Welltower"),
    Stock(ticker="AME", name="AMTEK"),
    Stock(ticker="LEN", name="Lennar"),
    Stock(ticker="ODFL", name="Old Dominion Freight Line"),
    Stock(ticker="NUE", name="Nucor"),
    Stock(ticker="LBRDA", name="Liberty Broadband"),
    Stock(ticker="ROK", name="Rockwell Automation"),
    Stock(ticker="TU", name="Telus"),
    Stock(ticker="CPRT", name="Copart"),
    Stock(ticker="TASK", name="TaskUs"),
    Stock(ticker="MQ", name="Marqeta"),
    Stock(ticker="FAST", name="Fastenal"),
    Stock(ticker="MCK", name="McKesson"),
    Stock(ticker="FERG", name="Ferguson"),
    Stock(ticker="MGA", name="Magna"),
    Stock(ticker="MTD", name="Mettler-Toledo"),
    Stock(ticker="STT", name="State Street"),
    Stock(ticker="AJG", name="Arthur J Gallagher"),
    Stock(ticker="AMP", name="Ameriprise"),
    Stock(ticker="VIACA", name="ViacomCBS Class A"),
    Stock(ticker="RMD", name="ResMed"),
    Stock(ticker="FITB", name="Fifth Third Bancorp"),
    Stock(ticker="WEC", name="WEC Energy"),
    Stock(ticker="MPLX", name="MPLX LP"),
    Stock(ticker="CBRE", name="CBRE"),
    Stock(ticker="ANSS", name="ANSYS"),
    Stock(ticker="CUK", name="Carnival"),
    Stock(ticker="FMX", name="Fomento Economico Mexicano"),
    Stock(ticker="TSN", name="Tyson Foods"),
    Stock(ticker="EQR", name="Equity Residential"),
    Stock(ticker="AVB", name="AvalonBay"),
    Stock(ticker="EFX", name="Equifax"),
    Stock(ticker="FNV", name="Franco-Nevada"),
    Stock(ticker="YUMC", name="Yum China"),
    Stock(ticker="WY", name="Weyerhaeuser"),
    Stock(ticker="SGEN", name="Seagen"),
    Stock(ticker="AWK", name="American Water Works"),
    Stock(ticker="DDOG", name="Datadog"),
    Stock(ticker="SWKS", name="Skyworks"),
    Stock(ticker="IBKR", name="Interactive Brokers Group"),
    Stock(ticker="VRSK", name="Verisk Analytics"),
    Stock(ticker="ES", name="Eversource Energy"),
    Stock(ticker="SYF", name="Synchrony"),
    Stock(ticker="CCEP", name="Coca-Cola Europacific Partners"),
    Stock(ticker="VIAC", name="ViacomCBS Class B"),
    Stock(ticker="MXIM", name="Maxim Integrated"),
    Stock(ticker="GRMN", name="Garmin"),
    Stock(ticker="TEF", name="Telefonica"),
    Stock(ticker="APP", name="Applovin"),
    Stock(ticker="KSU", name="Kansas City Southern"),
    Stock(ticker="BLL", name="Ball"),
    Stock(ticker="EPAM", name="EPAM"),
    Stock(ticker="LH", name="LabCorp"),
    Stock(ticker="TCOM", name="Trip.com"),
    Stock(ticker="TME", name="Tencent Music Entertainment"),
    Stock(ticker="ZBRA", name="Zebra Technologies"),
    Stock(ticker="GMAB", name="Genmab"),
    Stock(ticker="ZTO", name="ZTO Express"),
    Stock(ticker="ED", name="Consolidated Edison"),
    Stock(ticker="ZS", name="Zscaler"),
    Stock(ticker="U", name="Unity Software"),
    Stock(ticker="RYAAY", name="Ryanair Holdings"),
    Stock(ticker="ARE", name="Alecandria Real Estate Equities"),
    Stock(ticker="KEYS", name="Keysight Technologies"),
    Stock(ticker="HRL", name="Hormel Foods"),
    Stock(ticker="RCI", name="Rogers Communication"),
    Stock(ticker="CS", name="Credit Suisse"),
    Stock(ticker="ANET", name="Arista"),
    Stock(ticker="HES", name="HESS"),
    Stock(ticker="TAL", name="TAL Education"),
    Stock(ticker="WST", name="West Pharmaceutical"),
    Stock(ticker="O", name="Realty Income"),
    Stock(ticker="BKR", name="Baker Hughes"),
    Stock(ticker="NTRS", name="Northern Trust"),
    Stock(ticker="CAJ", name="Canon"),
    Stock(ticker="VRSN", name="VeriSign"),
    Stock(ticker="IP", name="international Paper Company"),
    Stock(ticker="FTV", name="Fortive"),
    Stock(ticker="EC", name="Ecopetrol"),
    Stock(ticker="RPRX", name="Royalty Pharma"),
    Stock(ticker="VMC", name="Vulcan Materials"),
    Stock(ticker="PKX", name="POSCO"),
    Stock(ticker="OXY", name="Occidental Petroleum"),
    Stock(ticker="IMO", name="Imperial Oil"),
    Stock(ticker="URI", name="United Rentals"),
    Stock(ticker="GWW", name="W.W. Grainger"),
    Stock(ticker="RNG", name="RingCentral"),
    Stock(ticker="MKC", name="McCormick & Company"),
    Stock(ticker="RCL", name="Royal Caribbean Group"),
    Stock(ticker="YNDX", name="Yandex"),
    Stock(ticker="CERN", name="Cerner"),
    Stock(ticker="ABC", name="AmerisourceBergn"),
    Stock(ticker="HUBS", name="HubSpot"),
    Stock(ticker="OKE", name="ONEOK"),
    Stock(ticker="FMS", name="Fresenius Medical Care"),
    Stock(ticker="UMC", name="United Microelectronics"),
    Stock(ticker="HIG", name="Hartford Financial Services Group"),
    Stock(ticker="TDOC", name="Teladoc Health"),
    Stock(ticker="CNHI", name="CHN Industrial"),
    Stock(ticker="CDW", name="CDW Corp"),
    Stock(ticker="WDC", name="Western Digital"),
    Stock(ticker="TLK", name="PT Telekommunikasi Indonesia"),
    Stock(ticker="FLT", name="FleetCor"),
    Stock(ticker="MLM", name="Martin Marietta Materials"),
    Stock(ticker="RF", name="Regions Financial"),
    Stock(ticker="PPL", name="PPL"),
    Stock(ticker="KEY", name="KeyCorp"),
    Stock(ticker="XP", name="XP Inc"),
    Stock(ticker="GIB", name="CGI"),
    Stock(ticker="TER", name="Teradyne"),
    Stock(ticker="STX", name="Seagate Technology"),
    Stock(ticker="DOV", name="Dover"),
    Stock(ticker="WPM", name="Wheaton Precious Metals Corp"),
    Stock(ticker="LNG", name="Cheniere Energy"),
    Stock(ticker="AEE", name="Ameren"),
    Stock(ticker="IX", name="Orix"),
    Stock(ticker="TTWO", name="Take-Two Interactive Software"),
    Stock(ticker="FTS", name="Fortis"),
    Stock(ticker="IAC", name="IAC"),
    Stock(ticker="XYL", name="Xylem"),
    Stock(ticker="CFG", name="Citizens Financial Group"),
    Stock(ticker="EXPD", name="Expeditors International of Washington"),
    Stock(ticker="EIX", name="Edison International"),
    Stock(ticker="QSR", name="Restaurant Brands"),
    Stock(ticker="ETR", name="Entergy"),
    Stock(ticker="NVCR", name="NovoCure"),
    Stock(ticker="CHD", name="Church & Dwight"),
    Stock(ticker="TSCO", name="Tractor Supply"),
    Stock(ticker="FUTU", name="Futu Holdings"),
    Stock(ticker="IR", name="Ingersoll Rand"),
    Stock(ticker="VTR", name="Ventas"),
    Stock(ticker="HPE", name="Hewlett Packard"),
    Stock(ticker="CVAC", name="CureVac"),
    Stock(ticker="GNRC", name="Generac Holdings"),
    Stock(ticker="MTB", name="M&T Bank"),
    Stock(ticker="FE", name="FirstEnergy"),
    Stock(ticker="HZNP", name="Horizon Therapeutics"),
    Stock(ticker="INVH", name="Invitation Homes"),
    Stock(ticker="QRVO", name="Qorvo"),
    Stock(ticker="TRU", name="TransUnion"),
    Stock(ticker="STNE", name="StoneCo"),
    Stock(ticker="AGR", name="Avangrid"),
    Stock(ticker="ALLY", name="Ally Financial"),
    Stock(ticker="PCG", name="Pacific Gas & Electric"),
    Stock(ticker="KB", name="KB Financial"),
    Stock(ticker="EXR", name="Extra Space Storage"),
    Stock(ticker="HAL", name="Haliburton"),
    Stock(ticker="CQP", name="Cheniere Energy Partners"),
    Stock(ticker="IT", name="Gartner"),
    Stock(ticker="WAT", name="Waters"),
    Stock(ticker="SPLK", name="Splunk"),
    Stock(ticker="PAYC", name="Paycom Software"),
    Stock(ticker="TXG", name="10x Genomics"),
    Stock(ticker="LYV", name="Live Nation Entertainment"),
    Stock(ticker="SHG", name="Shinhan Financial Group"),
    Stock(ticker="CINF", name="Cincinatti Financial Corp"),
    Stock(ticker="TRMB", name="Trimble"),
    Stock(ticker="TDY", name="Teledyne"),
    Stock(ticker="ALB", name="Albemarle"),
    Stock(ticker="TW", name="Tradeweb Markets"),
    Stock(ticker="ENPH", name="Enphase Energy"),
    Stock(ticker="COO", name="Cooper Companies"),
    Stock(ticker="ESS", name="Essex Property Trust"),
    Stock(ticker="SNN", name="Smith & Nephew"),
    Stock(ticker="HEI", name="Heico"),
    Stock(ticker="EXAS", name="Exact Sciences"),
    Stock(ticker="GPC", name="Genuine Parts"),
    Stock(ticker="UI", name="Ubiquiti"),
    Stock(ticker="SSNC", name="SS&C Technologies"),
    Stock(ticker="TFX", name="Teleflex"),
    Stock(ticker="DRI", name="Darden Restaurants"),
    Stock(ticker="SUI", name="Sun Communities"),
    Stock(ticker="AVTR", name="Avantor"),
    Stock(ticker="CE", name="Celanese"),
    Stock(ticker="AKAM", name="Akamai Technologies"),
    Stock(ticker="BR", name="Broadridge Financial Solutions"),
    Stock(ticker="J", name="Jacobs Engineering Group"),
    Stock(ticker="WMG", name="Warner Music Group"),
    Stock(ticker="INCY", name="Incyte"),
    Stock(ticker="VTRS", name="Viatris"),
    Stock(ticker="MAA", name="Mid-America Apartment Communities"),
    Stock(ticker="HTHT", name="Huazhu Group"),
    Stock(ticker="CLVT", name="Clarivate"),
    Stock(ticker="BXP", name="Boston Properties"),
    Stock(ticker="AVY", name="Avery Dennison"),
    Stock(ticker="CAG", name="ConAgra Brands"),
    Stock(ticker="RJF", name="Raymond James Financial"),
    Stock(ticker="AMCR", name="Amcor"),
    Stock(ticker="CMS", name="CMS Energy"),
    Stock(ticker="JBHT", name="J.B. Hunt Transport Services"),
    Stock(ticker="PEAK", name="Healthpeak Properties"),
    Stock(ticker="DVN", name="Devon Energy"),
    Stock(ticker="BIO", name="Bio-Rad Laboratories"),
    Stock(ticker="PODD", name="Insulet"),
    Stock(ticker="CTLT", name="Catalent"),
    Stock(ticker="PFG", name="principal Financial Group"),
    Stock(ticker="NVR", name="NVR"),
    Stock(ticker="PBA", name="Pembina Pipeline"),
    Stock(ticker="RLX", name="RLX Technology"),
    Stock(ticker="MKTX", name="MarketAxess"),
    Stock(ticker="OMC", name="Omnicom"),
    Stock(ticker="XM", name="Qualtrics International"),
    Stock(ticker="POOL", name="Pool Corp"),
    Stock(ticker="COUP", name="Coupa Software Inc"),
    Stock(ticker="BPY", name="Brookfield Property Partners"),
    Stock(ticker="AEM", name="Agnico Eagle Mines"),
    Stock(ticker="DRE", name="Duke Realty"),
    Stock(ticker="EDU", name="New Oriential Education & Technology"),
    Stock(ticker="LSXMB", name="Liberty Media"),
    Stock(ticker="BEN", name="Franklin Resources"),
    Stock(ticker="ON", name="ON Semiconductor"),
    Stock(ticker="EMN", name="Eastman Chemical"),
    Stock(ticker="ELAN", name="Elanco Animal Health"),
    Stock(ticker="NMR", name="Nomura Holdings"),
    Stock(ticker="CRL", name="Charlers River Laboratories"),
    Stock(ticker="AES", name="AES"),
    Stock(ticker="IEX", name="IDEX"),
    Stock(ticker="MKL", name="Markel"),
    Stock(ticker="ROL", name="Rollins"),
    Stock(ticker="VICI", name="VICI Properties"),
    Stock(ticker="ALNY", name="Alnylam Pharmaceuticals"),
    Stock(ticker="WPP", name="WPP"),
    Stock(ticker="ATUS", name="Atlice USA"),
    Stock(ticker="FTCH", name="Farfetch Limited"),
    Stock(ticker="TYL", name="Tyler Technologies"),
    Stock(ticker="XPO", name="XPO Logistics"),
    Stock(ticker="CVE", name="Cenovus Energy"),
    Stock(ticker="ELP", name="Paranaense de Energia"),
    Stock(ticker="STE", name="STERIS"),
    Stock(ticker="CAH", name="Cardinal Health"),
    Stock(ticker="PKI", name="PerkinElmer"),
    Stock(ticker="DISCA", name="Discovery"),
    Stock(ticker="ZEN", name="Zendesk"),
    Stock(ticker="PPD", name="PPD"),
    Stock(ticker="HOLX", name="Hologic"),
    Stock(ticker="PAGS", name="PagSeguro Digital"),
    Stock(ticker="HBAN", name="Huntington Bancshares"),
    Stock(ticker="AFRM", name="Affirm Holdings"),
    Stock(ticker="ACGL", name="Arch Capital Group"),
    Stock(ticker="TECH", name="Bio-Techne"),
    Stock(ticker="NLOK", name="NortonLifeLock"),
    Stock(ticker="BIP", name="Brookfield Infastructure Partners"),
    Stock(ticker="DGX", name="Quest Diagnostics"),
    Stock(ticker="SUZ", name="Suzano"),
    Stock(ticker="NWSA", name="News Corp"),
    Stock(ticker="VIPS", name="Vipshop Holdings"),
    Stock(ticker="BSY", name="Bently Systems"),
    Stock(ticker="CHKP", name="Check Point Software"),
    Stock(ticker="MPWR", name="Monolithic Power Systems"),
    Stock(ticker="PTC", name="PTC"),
    Stock(ticker="WAB", name="Westinghouse Air Brake Technologies"),
    Stock(ticker="WRK", name="Westrock"),
    Stock(ticker="ENTG", name="Entegris"),
    Stock(ticker="CG", name="Carlyle Group"),
    Stock(ticker="TXT", name="Textron"),
    Stock(ticker="LBTYA", name="Liberty Global"),
    Stock(ticker="HWM", name="Howmet Aerospace"),
    Stock(ticker="L", name="Loews"),
    Stock(ticker="LBTYK", name="Liberty Global"),
    Stock(ticker="WHR", name="Whirlpool"),
    Stock(ticker="FMC", name="FMC Corp"),
    Stock(ticker="DISCK", name="Discovery"),
    Stock(ticker="WYNN", name="Wynn Resorts"),
    Stock(ticker="DAC", name="Danaos Corp"),
    Stock(ticker="KIRK", name="Kirkland's"),
    Stock(ticker="AMTX", name="Aemetis Inc"),
    Stock(ticker="BGFV", name="Big 5"),
    Stock(ticker="GTIM", name="Good Times Rest"),
    Stock(ticker="LOB", name="Live Oak Bansch"),
    Stock(ticker="KEP", name="Korea Electric power"),
    Stock(ticker="MHK", name="Mohawk Industries"),
    Stock(ticker="CNP", name="CenterPoint Energy"),
    Stock(ticker="MOH", name="Molina Healthcare"),
    Stock(ticker="WIX", name="Wix.com"),
    Stock(ticker="LSXMA", name="Liberty Media"),
    Stock(ticker="DT", name="Dynatrace"),
    Stock(ticker="GDRX", name="GoodRx"),
    Stock(ticker="EMB", name="iShares JP Morgan USD Emerging Markets Bond ETF"),
    Stock(ticker="AMJ", name="JPMorgan Ultra-Short Municipal Income ETF"),
    Stock(ticker="JPST", name="JPMorgan Ultra-Short Income ETF"),
    Stock(ticker="WRBY", name="Warby Parker"),
    Stock(ticker="OLPX", name="Olaplex Holdings"),
    Stock(ticker="MEKA", name="MELI Kaszek Pioneer"),
    Stock(ticker="HCVI", name="Hennesy Capital Investment VI"),
    Stock(ticker="AMPL", name="Amplitude"),
    Stock(ticker="PRBM", name="Parabellum Acquisition"),
    Stock(ticker="CWAN", name="Clearwater Analytics"),
    Stock(ticker="SOVO", name="Sovos Brands"),
    Stock(ticker="BRLT", name="Brilliant Earth Group"),
    Stock(ticker="ARBK", name="Argo Blockchain"),
    Stock(ticker="ESMT", name="EngageSmart"),
    Stock(ticker="STER", name="Sterling Check"),
    Stock(ticker="FRSH", name="Freshworks"),
    Stock(ticker="TOST", name="Toast"),
    Stock(ticker="TYRA", name="Tyra Biosciences"),
    Stock(ticker="ONON", name="On Holding"),
    Stock(ticker="DH", name="Definitive Healthcare"),
    Stock(ticker="DICE", name="DICE Therapeutics"),
    Stock(ticker="BROS", name="Dutch Bros"),
    Stock(ticker="SRAD", name="Sportradar"),
    Stock(ticker="SQL", name="SeqLL"),
    Stock(ticker="RNXT", name="RenovoRx"),
    Stock(ticker="DRMA", name="Dermata Therapeutics"),
    Stock(ticker="DATS", name="DatChat"),
    Stock(ticker="WEBR", name="Weber"),
    Stock(ticker="DOLE", name="Dole"),
    Stock(ticker="OMGA", name="Omega Therapeutics"),
    Stock(ticker="COOK", name="Traeger"),
    Stock(ticker="ICVX", name="Icosavax"),]


    for stock in list_stocks: 
        db.session.add(stock)

    db.session.commit()


def undo_stocks():
    db.session.execute('TRUNCATE stocks RESTART IDENTITY CASCADE;')
    db.session.commit()